### ISSUE TITLE
PyNose as a python package

### ISSUE THREAD

**Issue by Niccolum** [JetBrains-Research/PyNose#35]
Hello.

Do you have any plans to use this plugin as separate entity, for example flake8-pynose or self-sufficient python package? For include this features in CI pipeline or precommit hook?

Thanks.

**Comment by SmirnovOleg** [comment]
Hey!

We are not planning to support PyNose as a Python package yet since it is based on the PSI, which is a part of the IntelliJ Platform SDK. But for CI purposes, I guess that it could be included in the pipeline as a linter for [Quodana](https://www.jetbrains.com/qodana/). We will discuss this possibility in the nearest future with the team, thanks!
