### ISSUE TITLE
Tool does not detect Magic Numbers (unittest)

### ISSUE THREAD

**Issue by BigYajuu** [JetBrains-Research/PyNose#47]
PyNose skips identifying numeric literal within the assertion statement as magic numbers.

![image](https://user-images.githubusercontent.com/62134513/195760514-28c8440f-4a10-4a27-b434-c2169f36fa14.png)

Here is the settings in `Editor > Inspections`

![image](https://user-images.githubusercontent.com/62134513/195760737-ec8c4e56-41b1-4c3c-b5cd-fe7537450771.png)

Tool used: pyNose 1.0.0
IDE: PyCharm Community 2022.2.3
Python: 3.10

**Comment by areyde** [comment]
@SmirnovOleg @OlesiaSub correct me if I'm wrong, but I think the issue here is that we chose to ignore "simple" numbers like 0, 1-10, etc. This is similar to other parts in the platform, for example, check out this: https://www.jetbrains.com/help/phpstorm/javascript-and-typescript-magic-number.html

When we originally developed the tool for analysis, we considered all magic numbers, yes, but when we evaluated it for actual usefulness, we discovered that highlighting such "obvious" numbers as 5 and 10 may be annoying for the user.

**Comment by BigYajuu** [comment]
Very interesting. The warning highlight does follow this pattern. Thanks for your explanation.

**Comment by areyde** [comment]
In case you need it for your research, you can change the list of ignored values here:

https://github.com/JetBrains-Research/PyNose/blob/master/plugin/src/main/kotlin/org/jetbrains/research/pynose/plugin/inspections/common/MagicNumberTestSmellVisitor.kt#L21

and rebuild your version of the plugin.
